export const FIELD_DEFINITIONS = [
  { id: "sequencialRegistro", name: "Seq.Registro", description: "Número sequencial do registro dentro do arquivo" },
  {
    id: "tipoRegistro",
    name: "Tipo Reg.",
    description:
      "Tipo de Registro: N - Nova Adesão Titular, C - Cancelamento, A - Alteração de Dados Cadastrais, U - Movimentação de Plano, D - Novo Dependente, I - Inclusão de Dependente, E - Exclusão de Dependente",
  },
  { id: "plano", name: "Plano", description: "Código do plano adquirido pelo beneficiário" },
  { id: "codigoBeneficiario", name: "Cód.Benef.", description: "Código do Beneficiário" },
  { id: "nomeCompleto", name: "Nome Completo", description: "Nome do beneficiário" },
  { id: "cpfBeneficiario", name: "CPF do Beneficiário", description: "CPF do beneficiário (sem formatação)" },
  { id: "rgRneBeneficiario", name: "RG/RNE", description: "Número do RG quando beneficiário maior de 18 anos" },
  { id: "orgaoExpedidor", name: "Órgão Exp.", description: "Órgão expedidor do RG" },
  { id: "nomeMae", name: "Nome Mãe", description: "Nome da mãe" },
  { id: "dataNascimento", name: "Dt.Nasc.", description: "Data de nascimento no formato DDMMAAAA" },
  { id: "sexo", name: "Sexo", description: "Sexo: 1 - Masculino, 3 - Feminino" },
  { id: "cns", name: "CNS", description: "Código do Cartão Nacional de Saúde" },
  {
    id: "estadoCivil",
    name: "Est.Civil",
    description: "Estado Civil: 1 - Casado, 2 - Solteiro, 3 - Divorciado, 4 - Viúvo, 5 - Separado, 6 - Outros",
  },
  { id: "logradouro", name: "Logradouro", description: "Endereço do beneficiário" },
  { id: "numero", name: "Número", description: "Numero do endereço" },
  { id: "complemento", name: "Complemento", description: "Complemento do endereço" },
  { id: "bairro", name: "Bairro", description: "Bairro" },
  { id: "cidade", name: "Cidade", description: "Cidade" },
  { id: "uf", name: "UF", description: "Estado" },
  { id: "cep", name: "CEP", description: "CEP" },
  {
    id: "tipoTelefone1",
    name: "Tipo Tel.1",
    description: "Tipo de Telefone 1: 1 - Residência, 2 - Comercial, 3 - Celular",
  },
  { id: "dddTelefone1", name: "DDD Tel.1", description: "DDD do telefone 1" },
  { id: "telefone1", name: "Telefone 1", description: "Número do telefone 1 (sem formatação)" },
  { id: "ramalTelefone1", name: "Ramal 1", description: "Ramal do telefone 1" },
  { id: "tipoTelefone2", name: "Tipo Tel.2", description: "Tipo de Telefone 2" },
  { id: "dddTelefone2", name: "DDD Tel.2", description: "DDD do telefone 2" },
  { id: "telefone2", name: "Telefone 2", description: "Número do telefone 2" },
  { id: "ramalTelefone2", name: "Ramal 2", description: "Ramal do telefone 2" },
  {
    id: "servidorPublico",
    name: "Serv.Público",
    description: "Servidor Público: 1 - Pessoa Física, 2 - Servidor Público",
  },
  { id: "tipoMovimentacao", name: "Tipo Mov.", description: "Tipo de Movimentação: 1 - Normal, 2 - Retroativa" },
  { id: "valorMensalidade", name: "Valor Mens.", description: "Valor com 10 inteiros e 2 decimais" },
  { id: "dataOperacao", name: "Dt.Operação", description: "Data da Operação no formato DDMMAAAA" },
  { id: "dataInicioVigencia", name: "Dt.Início", description: "Data de Inicio Vigência no formato DDMMAAAA" },
  { id: "motivoCancelamento", name: "Motivo Canc.", description: "Motivo de Cancelamento" },
  {
    id: "formaPagamento",
    name: "Forma Pag.",
    description: "Forma de Pagamento: 1 - Débito, 2 - Cartão, 3 - Cartão PL, 4 - Boleto, 5 - Folha",
  },
  { id: "banco", name: "Banco", description: "Código do banco" },
  { id: "agencia", name: "Agência", description: "Código da agência" },
  { id: "contaCorrente", name: "Conta", description: "Número da conta + dígito" },
  { id: "tipoConta", name: "Tipo Conta", description: "Tipo de Conta: 1 - Corrente, 2 - Poupança" },
  { id: "codigoVendedor", name: "Cód.Vendedor", description: "Código do vendedor" },
  { id: "codigoGerente", name: "Cód.Gerente", description: "Código do gerente" },
  { id: "codigoLoja", name: "Cód.Loja", description: "Código da loja" },
  { id: "codigoRegional", name: "Cód.Regional", description: "Código da regional" },
  { id: "contrato", name: "Contrato", description: "Contrato do cliente" },
  { id: "locacao", name: "Locação", description: "Locação" },
  { id: "email", name: "E-mail", description: "E-mail" },
  { id: "diaCobranca", name: "Dia Cobr.", description: "Dia do mês para cobrança" },
  {
    id: "grauParentesco",
    name: "Grau Parent.",
    description:
      "Grau de parentesco: 1 - Agregado, 2 - Cônjuge, 3 - Filho(a), 4 - Mãe, 5 - Pai, 6 - Tio(a), 7 - Enteado, 8 - Irmão(ã), 9 - Avô(ó)",
  },
  { id: "vinculoCpfTitular", name: "CPF Titular", description: "CPF do titular (sem formatação)" },
  { id: "codigoBeneficiarioTitular", name: "Cód.Ben.Titular", description: "Código do beneficiário titular" },
  { id: "funcionalMatricula", name: "Func/Matrícula", description: "Número de identificação no parceiro" },
  { id: "centroCusto", name: "Centro Custo", description: "Centro de custo" },
  { id: "carteirinha", name: "Carteirinha", description: "Número da carteirinha" },
  { id: "naturezaDocumentoIdentificacao", name: "Nat.Doc.ID", description: "Tipo do documento" },
  { id: "dataExpedicao", name: "Dt.Expedição", description: "Data de expedição do documento" },
  { id: "passaporteCarteiraCivil", name: "Passaporte", description: "Passaporte ou carteira civil" },
  { id: "atividadePrincipalDesenvolvida", name: "Atividade", description: "Atividade principal" },
  { id: "informacaoAdicional1", name: "Info.Adic.1", description: "Campo adicional" },
  { id: "informacaoAdicional2", name: "Info.Adic.2", description: "Campo adicional" },
  { id: "informacaoAdicional3", name: "Info.Adic.3", description: "Campo adicional" },
]
